# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [19]:
# Your code here
import numpy as np
import random
def create_random_matrix(rows,columns):
    new_array = np.zeros([rows,columns])
    for x in range(0, new_array.shape[0]):
        for y in range(0, new_array.shape[1]):
            new_array[x][y] = random.randrange(1, 10)
    return np.array(new_array)

In [30]:
mat_A = np.array(create_random_matrix(4,4))

mat_B = np.array(create_random_matrix(4,4))

mat_C = np.array(create_random_matrix(4,4))
type(mat_C)

mat_B_plus_C = mat_B+mat_C

In [31]:
print(mat_A.dot(mat_B_plus_C))
print("should be equal to...")
print(mat_A.dot(mat_B)+mat_A.dot(mat_C))

[[235. 218. 215. 190.]
 [240. 202. 280. 190.]
 [325. 289. 348. 263.]
 [265. 238. 252. 212.]]
should be equal to...
[[235. 218. 215. 190.]
 [240. 202. 280. 190.]
 [325. 289. 348. 263.]
 [265. 238. 252. 212.]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [34]:
# Your code here 
print(mat_A.dot(mat_B.dot(mat_C)))
print("should be equal to...")
print(mat_A.dot(mat_B).dot(mat_C))

[[2800. 2364. 2106. 1366.]
 [3050. 2556. 2224. 1553.]
 [3918. 3273. 2920. 1968.]
 [3092. 2598. 2304. 1540.]]
should be equal to...
[[2800. 2364. 2106. 1366.]
 [3050. 2556. 2224. 1553.]
 [3918. 3273. 2920. 1968.]
 [3092. 2598. 2304. 1540.]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [35]:
# Your code here 
print(mat_A.dot(mat_B))
print("should NOT be equal to...")
print(mat_B.dot(mat_A))

[[ 92.  87. 127. 100.]
 [ 85.  79. 142. 137.]
 [111. 106. 188. 168.]
 [ 94.  88. 144. 124.]]
should NOT be equal to...
[[106. 112. 110.  83.]
 [101.  99.  96.  88.]
 [157. 145. 161. 133.]
 [140. 130. 143. 117.]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [41]:
# Your code here 
vec_x = np.array(create_random_matrix(4,1))
vec_y = np.array(create_random_matrix(4,1))
print(vec_x)
print(vec_y)

[[3.]
 [5.]
 [2.]
 [5.]]
[[1.]
 [9.]
 [2.]
 [9.]]


In [42]:
vec_x_transp = vec_x.T
vec_y_transp = vec_y.T

In [43]:
print (vec_x_transp.dot(vec_y))
print ("should equal...")
print (vec_y_transp.dot(vec_x) )

[[97.]]
should equal...
[[97.]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [5]:
# Your code here 
print(mat_A.dot(mat_B).T)
print("should equal...")
print(mat_B.T)

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 